# -*- coding: utf-8 -*-
"""Day-1_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3hZPzr1IXv8y8uJ-atg30fdYVgPcMAP
"""

#Write a program in Jupyter Notebook to declare variables of different data types (integer, float, string, and boolean). Print each variable and its type.
a=10
print(a)
print(type(a))

A=int(input("Enter integer value:"))
print(A)
print(type(A))

b=10.1
print(b)
print(type(b))

B=float(input("Enter float value: "))
print(B)
print(type(B))

c="name"
print(c)
print(type(c))

C=input("Enter your string value:")
print(C)
print(type(C))

d=True
print(d)
print(type(d))