# -*- coding: utf-8 -*-
"""Day-2_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-e4QrrG8349etPfcIsGthkhkP6zxSDh
"""

#Create a List, tuple and Dictionary with 5 elements in it and how to access few elements based on the index. Try  with different examples
my_list = [10, 20, 30, 40, 50]
my_tuple = ("apple", "banana", "cherry", "orange", "mango")
my_dict = {"name": "Alice", "age": 25, "city": "New York", "job": "Engineer", "hobby": "Reading"}

print("Element at index 0:", my_list[0])
print("Element at index 3:", my_list[3])
print("Last element:", my_list[-1])

print("Element at index 1:", my_tuple[1])
print("Element at index 3:", my_tuple[-2])
print("First element:", my_tuple[0])

print("Value for key 'name':", my_dict["name"])
print("Value for key 'city':", my_dict["age"])
print("Value for key 'hobby':", my_dict["hobby"])