# -*- coding: utf-8 -*-
"""Day-3_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnF75-x9Lr8nEmqYnP0pGDuVngVm-EJB
"""

'''Write a Python program that takes a student's marks in three subjects as input.
If the average is greater than or equal to 90, print "Grade: A".
If the average is between 80 and 89, print "Grade: B".
If the average is between 70 and 79, print "Grade: C".
Otherwise, print "Grade: Fail".'''
s1=float(input("Enter marks in subject 1: "))
s2=float(input("Enter marks in subject 2: "))
s3=float(input("Enter marks in subject 3:"))
average=(s1+s2+s3)/3
if average>=90:
    print("Grade: A")
elif average>=80 and average<=89:
    print("Grade: B")
elif average>=70 and average<=79:
    print("Grade: C")
else:
    print("Grade: Fail")